### PR TITLE
Social Auth

### PR DESCRIPTION
**Pull request by bencevans**
A few questions from starting work on this @benjie ...
1. How do you wish to do database migrations, I need to add a`twitterId`, `facebookId` and `githubId` into the user table. Although this is a trivial migration is it worth setting up Sequelize migrations now?
2. I've used `passport` as everyauth kinda blows nowadays due to lack of continued service support and other issues. Passport handles it's authentication by mounting a users profile to `req.user` for each request. Looking around quite a lot will be updated to use that structure. Are you ok with this or would you prefer modding passportjs to use your custom authentication/session handling?
3. Do you use JSLint or equivalent, if so you might want to publish the preferences for the project ;)

### CODE REVIEW

**Comment by benjie** [comment]
@bencevans 
1. If you wanted to set up Sequelize migrations then that'd certainly help anyone who has a checkout of the app (there's a few of us now). I regret choosing Sequelize, I'm not a fan. If you don't fancy setting it up then I am not opposed to manual migrations; or even just manually sourcing a v1-to-v2.sql file (e.g. with ALTER TABLE statements). Keep in mind SQLite sucks at ALTER TABLE - you can only add.
2. `passport`: good plan :) `req.user`: I don't mind this being rewritten; can just change all the existing `req.user` to `req.userModel` or similar?
3. I'm not a fan of JSLint; it takes too long to configure and most of it's warnings are stupid (`(function(){}())` over `(function(){})()`?! No way, Crockford, that's so wrong!). I shall be the final arbiter of code style; if I don't like yours I'll just rewrite it :P Having said that I wrote most of this whilst watching TV so it's a bit of a mess already. Not to mention it's full of repeating chunks of code and _oh just try not to look alright, it's awful_.

Speaking of code style, I don't like brackets in CoffeeScript spanning more than one line. e.g.

```
passport.use new FacebookStrategy(
  clientID: env.FACEBOOK_APP_ID
  clientSecret: env.FACEBOOK_APP_SECRET
  callbackURL: env.SERVER_ADDRESS + '/auth/facebook/callback'
, (accessToken, refreshToken, profile, done) ->
  User.findOrCreate "bob", (err, user) ->
    return done(err)  if err
    done null, user
)
```

Would become:

```
options =
  clientID: env.FACEBOOK_APP_ID
  clientSecret: env.FACEBOOK_APP_SECRET
  callbackURL: env.SERVER_ADDRESS + '/auth/facebook/callback'
passport.use new FacebookStrategy options, (accessToken, refreshToken, profile, done) ->
  User.findOrCreate "bob", (err, user) ->
    return done(err)  if err
    done null, user
```

**Comment by bencevans** [comment]
- [x] GitHub Connection
- [x] Twitter Connection
- [x] Facebook Connection
- [x] Ability to connect social account to an existing email/password account
- [x] Ability to sign in using connected social accounts (not registering using though)
- [x] Errors for no account found
- [x] Document accepting social auth (setting key/secrets etc)

Actually getting something together now @benjie! ...

screenshot from 2013-10-19 23 06 13

**Comment by bencevans** [comment]
@benjie  Ok, I think we're there. Pull and take it for a spin!

**Comment by benjie** [comment]
Nice one @bencevans, all looks good - it's now live! :D Sorry it took so long, I've been having a very hectic time of late.

**Pull request closed without merging**
